apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    "operatorframework.io/suggested-namespace": openshift-logging
    alm-examples: |-
      [
        {
          "apiVersion": "grafana.example.com/v1alpha1",
          "kind": "GrafanaCloudLogForwarder",
          "metadata": {
            "name": "grafanacloudlogforwarder-sample",
            "namespace": "openshift-logging"
          },
          "spec": {
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.12.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: grafanacloud-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: GrafanaCloudLogForwarder
      description: GrafanaCloudLogForwarder is the Schema for the grafanacloudlogforwarders API
      displayName: Grafana Cloud Log Forwarder
      name: grafanacloudlogforwarders.grafana.example.com
      version: v1alpha1
      specDescriptors:
      - displayName: URL
        description: URL of loki datasource
        path: url
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:text'
      - displayName: Username
        description: The username from the loki endpoint
        path: username
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:text'
      - displayName: Password
        description: API password for accessing loki datasource
        path: apipassword
        x-descriptors:
          - 'urn:alm:descriptor:com.tectonic.ui:password'
  description: Grafana Cloud is a completeobservability stack for metrics, logs, and traces that's tightly integrated with Grafana. Leverage the best open source observability software without the overhead of installing, maintaining, and scaling your observability stack.
  displayName: GrafanaCloudLogForwarder
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAWIAAAAmCAYAAAD+4pG0AAAACXBIWXMAAAsSAAALEgHS3X78AAAPhklEQVR4nO1d0Wscxxmf04YokSKd/gOdndiy8yLlqdAXbTYQyJPOeS1EJxIaCDU611AaCPhUAikBtydcWloafC4E+tScoBDIw+bupdCn3L0ksq3Ed/+BzpKdOC9XZv2b62rvm9nZ3dm7lbI/WEisu5tvZmd+3zfffN83heFwyNLE4BcvLzHGyowxmzFWYoytB5prM8Z6jLEWY6xZ/PTrw1QFypEjR46MITUiHrz1MifeKmNsI+JX7zDGasV/fN3L2FjlyJEjRyowTsSDrcvc6m0Qlm9U7HqEfPubTFrIjuMswcpfw7OEP3F5O3haruvmFn6OMw3HcfiarwT6yOd+K3/z43AcpwLvwAjPmGzg4TuXywXLI+GigZ/b5i4N/puLf/+mY+D3jACDyC39VcXvjXYBjuNw10vDdd1GVvqQIwfIUxgRQRyCSHXXHf+tG8S/50RMoxI0VI0R8cN3L1eYxW6b+j1gmb/Mh+9ethf/Ol0yBgHXIFMU8AFfdxyHf7fqum5zmv1IG4GdggzNCIs8hyHg3ZQ1DAkPjuMM+Lvi89513dxVmCKMEPHD97RJeIAtux9hLoyiR8bvXbYX/zx5MsbkbRpwtXAC/8xxnD2uEc+aywLjVMUTtiPKdwcThuM4VRgSUXar/LOb/HEc505OyOkhMRE/vHppjVmsrviI0Kr1xVv7Y0T68OoloaXHzHUf+IRo8rYWb+1PjMAcx1nD9sqEq0WAuy06juOUz4pVCBJu6VhZ/DA2X8yTg0FDghNymRN67mYzj5mkv8h9wgWLFQuW99/BZ69gsdLirf0KRcIcnFgXb+03Fm/t2wWLXSlYbCD5rWX4nycCDRIeIMJjizH2iuu6Bf7w/2aMXcHfBpLvLmNxnBU0NUmY5dbw5IA53DNAwgJ8LdyGmy2HQSSyiI+uX+IuCdkCvLZwc19lKY9hob7fPLp+qaSwrjaOrl+yF27up3oIgIMMGQlzcuX9qlPuBVi5/GmGbNfL6fVgcoDvXLXQ277/7uUn6ZOBpiHRwGc6YpfiOI7w75cV7/WG4ziHrutGWt855EjmmrCYTDPuLnwcjYQFFm7uHx795pKtIOMaDoPSRFMygbt8gupurUHUNcdxGiBvEU2xdYYOq6rEv3VxMJmT7hTgc0fIDImajETxzvhTh0EiC0UtY07nMIDIRHz0/oogwRKzyAiC7sJHd6nFqY2Fj/cPj95f4ZbWV8R31o/eXyktfHQ3FT8jtl2UAuC+zWCspBZA3GUcmKydMR9bcKwGUZRVjlTQkET3RDUk+OdszNs/+v6067puojWe4yRCifj4A494K7BCuZ82DEZe0MJHdzvHH6zcwSFBEKloY58rIYh2XBL246xt5bCNDaKZk/D0wA+BJdmsnITtONE6fN5yVwTWXH5YlwKkh3XHN1bs4xsrLWaxL5nFNj3r1/LcEaqn/8KHd81tR7nrg24vLf8q5csdnBV/7oSQk/B0QSn7QVwSFgD5lnISTgekRXy8s1JnM15m21MUtNs2Ggnwws7d3vHvVvrENkuVLJAElNVbnUbMLw5b/IvKy86D366MbCZqHDqybSMs2DK+5/f79cUBIyzaQ3y+HmhDJ0OwIrGUlbL5+lwxKV/wM67r2uz/h4yiGJVQvgNRfCoJ4WBnVfGNtV+5t9GXhjgnIN71SM6I7ZYlLomyiTmc5jrAvC75ygXw93B4ms5S8B5FQpModdDT2SGeIOLjDy8uef4lK6RQj5yYzYdkWcMeMblMxvV6wCAG2+lP0QJYCpBRB4d+lKvGjzF5QYw1xSn4Mp4NHNLwiJAaQYg6u53lqNmHKct34jNoS+ZDLaKNjTiZkCDgGtLzZVjHs4309wrxruOCMiTaWT00BflyxUwpkBvsZHZfI6wfUK7BMajqkjmh2EMVos+dWZHNe8dxuoiyknLJCSIuWCdO9vVwkpSNb0sLlre4xibpo99fXJv/7T2T2pJyP2Qp1le1uAUGEotQ57sCRYQn2b5CRqkhgXxx3UVfan5OZEJu6SjjmMk/6z5L3wSotZvJcwmh6DTGK5jdp9qhUmV2o8zhoGJXAsRf1+jDKuKvq7KIrxERP/r4Ys3zBavRFVsG36dE3GFx/jf3zPsH5YeDa0S6dBJQ2/zTlnQRJGEdC1oGU0kAUiSUTzeBJCn4AmIqMk6YgVlMMAZ+GagFPshabRNYkI0Y5XEZxmmNE+C0XRYxDAiGOUta9R4RP7p5kYeiqaIdeH2E6vx1mmgf3by4lNqBliXVaLcf/eEi16q1+V/fM+E+GGtHZ0uHBWAqrrmRMOJgZP3A4lAtcH/dD5Ok21a4MEZ9m6J8srZUJMrdIS3q3WiScBfGSylG0ShdUIZEFl0S0XfdJ7GKZKm1adVrgSUclYQFSAPiqUVsDVXFQLbmq/eVRDd//d5haqmr1lB1MLfsEfLuBc/PNL99fxon9rakBGActDTdO10E5ZPWDpSDTKY9fLcT+E4Z/s2klmYL/lspQF7Tks+PHX+GpO/QLEj8RbRN+WBlW9MBtt5NP2HALxqmhOKAMlgyddCFrbms33ewA+1Aaa35atAEx1eUCEg7sWsMeH+yAmd9vFt+KN3BfBIXZCgV8DOPb11YKshdEtfmrqpJOG0U5BaxH3xxdh7/6YI996v7cSdfWpEYpqETDyojQqm/E6TeTOgu0IXMbzlJ+V4Jkj3+35a0sYmCN35SlaV3S98RrOoK2pBlv505+A4ygxChdcF162X4YedEZdmuo3DWpF0vsrW1EzRAfOUO6uiH1GCb8WJy6Vjd9tzV+9N39PNaFuHxy/wpMou1Hv/lQtwDptMQJjMIC0WCFqbI4ZrOoRMSV/YSSypBRuTbUfkY0Uaf+FNQWVMWslbiBNxeP6X4dMqylZHwCBhHG+MaxESz+2ANU0bAGAkHgb9fk/19hllDm1lDRjxTJ+HHf3tpjVnDtu/pSmQVT5FZQ2MWPLR4GHrwi0Z9ZJXZVNDJWqMWdztiVl8lpnw6yIJ8Om1RnxlthbEoKYWiHXcOMr6j89kzAFmMfqgBhPGk5s063sOkQLlC+mEk7OtHPVAEa4RnmMXIjsy9czD109a5Xx50gp1//MlLIlhe5tfeePzJS/bc2wdRDyqocoF2WOQErLjI5I+U0eBvhcms4z+mJkskpconvuM4zZRcFJR8kcYP8jXiHphoEmUYQVCurG6MmF1T/mJqbkzch6rAWE2SKDH63ABB+FpwrNYmmM1JjWfUkqA1KoRyhvtgidq/JGtnAXNvHxzOvX1QL8wwW1G7OE5dCGrhpbJ1xPY8qESorVccUIo1zul5WoqYki9OW9OOCDAS7ogdDuUGiQqKjDJx7iGrSRLjp2QJO5NC4rkrU9QzUh9sxvH81kGHzTDbq5YhnmS1KKgBLWu6J6KC8m2ZIpax09mYYT5phQZlXb4kiCtTYosOCzzorikmSHxJG3H6nLk6JjHn7pihOwP/a9DXmnpGlQk8/9ZBh1nDvZHcM6On+P2nL0bSlBLLpGj6QEDh8P+pFFNJy/ecBUx73VDGRF6u8hRgRhKBsPr9P188FWTMLNaR9CGO/JQvtWr4QIAi3L7BTKExbQtXSFSkteUb62fG5NMFZZ1FnifYcZlKWKHm1npGreI4ayrtg7nI7yEmN4y1w33EHYmf9VSE1khkZxp1kyk0qO2d79qjREBaJPWyTd4BRhFEHJ95WpYUJV+cthLXh04I8kwhxjwxts7gnqD8zQ0TxkRMhSnzi8bpN+VrDjNgtPodIUJKRyZVO2S/uUXckliUtR/+dQqsYsu7KYSSP04B7EMJKawiuDz2eCCgmzrlbxuu8EZtT7ejLCJkQKWVikvJtxlDvknVmiCBHQzlytJWqookhySgFFRiYwJRKl8luDg0eBhdREKMbvsyl56fiJMQpY5ioBRK1PEgjY6Z5978tsms4YDwEy9nIZZYhR/2zi8xa1imYoqfe/PbWFt9kCIVNbKKUpRRNeASQsGorJqBacsOmUaUH7ahsxBBiKnd0gv5ZFbb1OWLCEqBbusQDPraMq3wFLHJfP72olq1mL/+TENe+S4OqVNjVY8gD6XA24G4eoqIQ3cpERQiJcMyxicUqot2n97Qwctf0lbl5g//Pp/dQyTLq51cJOROmnlVlpAFXzRf8oEPm0Bcg8N66CmKnFRTulaImlShigSW5lcTSLulFLwgijD54lY5SwN1idLjFdvqMgLwFQpKy6qvSsIhi7BqtVwVII4OYYluxAg/k7n9+E5TupagCFQXCY8gixxRKfkoChE7ZkrJbcLtKAXmrqxGxdOiP6hDLKsNuvnk8/Ne4e7ZN77LBCk/+fy8d7tswZI61xPFwCJhoKxY9KI+ap8o1CMq9IctMq06t3GAO8YqhAxCkXQDY7QkKc6dChTyFbMgny4wT2QLbBs1JZqB+VFO260CuWy0q5q/olKef8tdwvwthyi8OEk4tcAlpMynHETRn5ZPflnRH6YoeE8lIm2A8OuiCJPG78tQk4zNtq8wVQsJKGIspZawgEfEs298d/jki/P8w59JPudVOXvyxfnbshS9CWLJi32Woz/7enKFgepJ4jYHWXvLMbOiUiNhH1QLcXXaPtZTIJ8WcH2VLZkHRmoNx5TrEESgsrzFbSFRqgcO4l4gCgVsS3aIm2KseP3nEPQVPl1ZpuIqFOZtjd9X9aGnUL7L4t+jtjG6PHT29e+4r3g3pJYDf9an/KyGyGfyFFqkWJuqB9BF1a/UdxYhxVJ0YSrb79TJFwUoEpRkjqQSW+0bY1Pzt48iPUnmb9KiTX1V4Su4+nZi/G5X18hE/+O0IdoZm7cnbnGefe1BlVlsV7PaWRafrdnXHhitosZfOBbaqwl2A31YwWuTvFkggSLpo7+p1hvxybcb8asTkS8KMEeuxCDV3TSrsBmavwMQT+L5C3nKMYlsT0cGFOGJMqfaUcPQ0MZWxPct2hlTImPX6c/aD6oFi11R1HHI4sNl3Zq1H6RmaXJ/FC4SfAUvOcwaG4AAr7iuO7VryH0L8RzkUU2cLhRGaVIXTkK+albliwJEhJRQ7lBVP0LMjXOqW60Nyybm76sa4yzQBtnw8a6ZvBEDRHYOaylMFi7vq5zAI1S2q2ooH2EghZYtlbTRwPveCXnf3bB2CsPhkPzmj/85t4RT4TCn/bTh3YT77M8fTCUPXXLKr3WF9rQAmUu+YPdWlmTOuny68F0RL+ZID/3IhBIhrrBn4oaMScuIyImSL2PS2FgR76GDWzSMzieiD9rtSIlY4Mf/lsSJtbgkNAuHKG10svHsz3qnoaB7jhw5ctBgjP0P1DoF6+ryZMcAAAAASUVORK5CYII="
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - grafana.example.com
          resources:
          - grafanacloudlogforwarders
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - grafana.example.com
          resources:
          - grafanacloudlogforwarders/finalizers
          verbs:
          - update
        - apiGroups:
          - grafana.example.com
          resources:
          - grafanacloudlogforwarders/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - logging.openshift.io
          resources:
          - clusterlogforwarders
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - logging.openshift.io
          resources:
          - clusterloggings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: grafanacloud-operator-controller-manager
      deployments:
      - name: grafanacloud-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.7.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/yoza/grafanacloud-operator:1.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                env:
                  - name: WATCH_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: grafanacloud-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: grafanacloud-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - clusterlogging
  - clusterlogforwarder
  - grafanacloudlogforwarder
  links:
  - name: Grafanacloud Operator
    url: https://grafanacloud-operator.domain
  maintainers:
  - email: support@grafana.com
    name: 'Richard Lam'
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
