# permissions for end users to edit grafanacloudlogforwarders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafanacloudlogforwarder-editor-role
rules:
- apiGroups:
  - logs.grafana.com
  resources:
  - grafanacloudlogforwarders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logs.grafana.com
  resources:
  - grafanacloudlogforwarders/status
  verbs:
  - get
